FROM alpine-jdk:base
MAINTAINER javaonfly
COPY files/fxdiscovery-service-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/fxdiscovery-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8761