FROM alpine-jdk:base
MAINTAINER javaonfly
COPY files/fxrate-configserver-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/fxrate-configserver-0.0.1-SNAPSHOT.jar"]
EXPOSE 9090