server:
  port: 8304

spring:
  application:
    name: zuul-proxy
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false    

zuul:
  prefix: /api
  routes:
    fxrate-service:
      path: /fxrate-service/**
      url: http://localhost:8302 
    fxratedb-service:
      path: /fxratedb-service/**
      url: http://localhost:8301    
    