server:
  port: 9090 
     
spring:
  application:
    name: fxrate-configserver         
  cloud:
   config:
     server:
#      monitor:
#        github:
#        enabled: true      
      git:
        uri: https://github.com/ashrujitpal/fxrate-config.git
        force-pull: true
        username: ashrujitpal@gmail.com
        password: kolkata@1

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2  
  
  
 